Repository ml5js/ml5-library, pull requests merged in 2022-01, with the labels that each got.

#1237 [issue-1230] fix: fix docs to correctly reflect working example
  docs/reference/neural-network.md
Labels: bug, documentation, neural-network

#1256 README.md
  README.md
Labels: documentation, ready for release

#1250 Added links to Discord
  docs/README.md
Labels: documentation, ready for release

#1242 added direct link to twitter thread
  docs/reference/word2vec.md
  src/Word2vec/index.js
Labels: documentation

#1241 Rename LICENSE to LICENSE.md
  LICENSE.md
Labels: feature request

#1266 feat: #1265 Integrate release drafter for automating releases
  .github/release-drafter.yml
  .github/workflows/main.yml
  .github/workflows/publish.yml
  README.md
Labels: devops, SEMVER/minor

#1267 fix: #1265 - adds npmrc and updates publish yaml
  .github/workflows/publish.yml
  .npmrc
Labels: devops, SEMVER/patch

#1270 devops: testing - publish.yml workflow
  .github/workflows/publish.yml
  README.md
  package-lock.json
  package.json
Labels: devops, SEMVER/patch

#1271 chore: try rm specific node version
  .github/workflows/publish.yml
  README.md
  package-lock.json
  package.json
Labels: devops, SEMVER/patch

#1272 refactor: try using publish-npm
  .github/workflows/debugging.yml
  .github/workflows/publish.yml
  README.md
  package-lock.json
  package.json
Labels: devops, SEMVER/minor

#1273 chore: bump pkg - debugging
  .github/workflows/debugging.yml
  .github/workflows/publish.yml
  README.md
  package-lock.json
  package.json
Labels: devops, SEMVER/patch

#1274 Joeyklee.devops publish workflow
  .github/workflows/publish.yml
  README.md
  package-lock.json
  package.json
Labels: devops, SEMVER/patch

#1275 fix: linting and bump pkg
  .github/workflows/publish.yml
  README.md
  package-lock.json
  package.json
Labels: devops, SEMVER/patch

#1244 Fixed: CharRNN Example Input text not showing
  examples/p5js/CharRNN/CharRNN_Interactive/index.html
  examples/p5js/CharRNN/CharRNN_Interactive/sketch.js
Labels: examples, char-rnn, SEMVER/patch

#1277 chore: bump pkg
  README.md
  package-lock.json
  package.json
Labels: devops, SEMVER/patch

#1157 Update darknet.js
  src/ImageClassifier/darknet.js
Labels: ready for release, SEMVER/patch

#1276 docs: updates release notes
  docs/styleguide/maintenance-notes.md
Labels: documentation, SEMVER/patch

#1278 chore: bump pkg
  README.md
  package-lock.json
  package.json
Labels: SEMVER/patch

#1280 Remove unnecessary sketch file import from KMeans Mouse Clustering example
  examples/p5js/KMeans/KMeans_mouseClustering/index.html
Labels: SEMVER/patch

#1251 Fixed broken links in docs
  docs/reference/facemesh.md
Labels: documentation, SEMVER/patch

#1185 Use the 'face' event for Facemesh event emitter
  docs/reference/facemesh.md
  examples/p5js/Facemesh/Facemesh_Image/sketch.js
  examples/p5js/Facemesh/Facemesh_Webcam/sketch.js
  src/Facemesh/index.js
Labels: ready for release, SEMVER/minor

#1184 Use the 'hand' event for Handpose event emitter
  docs/reference/handpose.md
  examples/p5js/Handpose/Handpose_Image/sketch.js
  examples/p5js/Handpose/Handpose_Webcam/sketch.js
  src/Handpose/index.js
Labels: ready for release, SEMVER/minor

#1284 chore: bump version
  README.md
  package-lock.json
  package.json
Labels: SEMVER/patch

#1285 chore: package bump
  README.md
  package-lock.json
  package.json
Labels: SEMVER/patch

#1282 added KMeans_mouseClustering to examples page
  docs/reference/kmeans.md
Labels: documentation, kmeans, SEMVER/patch

#1286 chore: checkin package lock
  package-lock.json
Labels: SEMVER/patch

#1287 V0.9.3
  README.md
  package-lock.json
  package.json
Labels: SEMVER/patch
