Repository ml5js/ml5-library, pull requests merged in 2022-03, with the labels that each got.

#1311 Code clean-up: Video class.
  src/StyleTransfer/index.js
  src/utils/Video.js
Labels: SEMVER/patch

#1307 Bug fix: `callCallback` should reject the returned Promise
  src/utils/callcallback.js
Labels: bug, SEMVER/patch

#1315 tests: adds test for callCallback util
  examples/examples.json
  karma.conf.js
  package-lock.json
  package.json
  src/utils/callcallback_test.js
Labels: SEMVER/patch

#1318 guard all `window` references
  src/BodyPix/index.js
  src/FaceApi/index.js
  src/utils/modelLoader.js
  src/utils/p5Utils.js
Labels: SEMVER/patch

#1325 Update README.md
  README.md
Labels: documentation, SEMVER/patch
