Repository ml5js/ml5-library, pull requests merged in 2022-02, with the labels that each got.

#1288 chore: bump pkg - testing automated version bumping
  .github/workflows/debugging.yml
  README.md
  package.json
  scripts/updatePackageVersion.js
Labels: SEMVER/patch

#1291 fix: rm v number
  .github/workflows/publish.yml
Labels: SEMVER/patch

#1292 chore: try to push with pat
  .github/workflows/debugging.yml
  README.md
Labels: SEMVER/patch

#1297 Fix typo in examples/CONTRIBUTING.md
  examples/CONTRIBUTING.md
Labels: documentation, SEMVER/patch

#896 added getData method
  src/NeuralNetwork/NeuralNetworkData.js
Labels: ready for release, SEMVER/minor

#1247 perf(ImageClassifier): use urls directly from teachablemachine
  src/ImageClassifier/index.js
Labels: ready for release, teachable-machine, SEMVER/patch

#1246 Disabled p5 web editor examples
  docs/reference/charrnn.md
Labels: documentation, SEMVER/patch

#1293 docs: updates docs with latest release process
  docs/styleguide/maintenance-notes.md
Labels: SEMVER/patch

#1036 DBSCAN Clustering Algorithm
  examples/examples.json
Labels: feature request

#1062 PoseNet examples
  examples/p5js/PoseNet/PoseNet_image_single/sketch.js
Labels: SEMVER/patch
